### ISSUE TITLE
CosmWasm VM fails when tendermint's `wasm32-bindgen` feature is enabled for `celestia-types`

### ISSUE THREAD

**Issue by Farhad-Shabani** [eigerco/celestia-node-rs#131]
## Problem Statement

We are currently engaged in the development of an IBC light client for Sovereign SDK blockchains. In this process, the `celestia-types` crate is employed for importing relevant types. 
I have encountered an issue during the compilation of our CosmWasm smart contract with the `wasm32-unknown-unknown` target. The contract relies on `celestia-types` as one of its dependencies, and during compilation, the `celestia-types` is compiled with the [`wasm32-bindgen` feature](https://github.com/eigerco/celestia-node-rs/blob/69647d66c489b4b7df3cf1a7df24c1c79abe3111/types/Cargo.toml#L30) enabled for the `tendermint-rs` dependency. This leads to an error when the CosmWasm VM attempts to load the contract (this [issue](https://github.com/informalsystems/sovereign-ibc/issues)). Locally, I could manage this issue by disabling the `wasm32-bindgen` feature and the compiled Wasm file works as expected.

## Proposal

To not enforce the `wasm32-bindgen` feature for the wasm32 targets. Instead, defining a new feature, such as `wasm-bindgen = ["tendermint/wasm-bindgen"]` to selectively enable the `wasm32-bindgen` feature where necessary.

## Side Question
Additionally, I noticed there is a `wasm-bindgen` feature for the `time` dependency so we could have e.g. `wasm-bindgen = ["time/wasm-bindgen"]` instead of [this](https://github.com/eigerco/celestia-tendermint-rs/blob/ef58b85e3e8b35b0f94b822d3996613539dcddd7/tendermint/Cargo.toml#L65) within the `celestia-tendermint-rs`, so the unit tests would pass too. Was there any specific reason for introducing the `Instant` dependency in this context?

**Comment by oblique** [comment]
> To not enforce the wasm32-bindgen feature for the wasm32 targets. Instead, defining a new feature, such as wasm-bindgen = ["tendermint/wasm-bindgen"] to selectively enable the wasm32-bindgen feature where necessary.

Initially we decided to treat all WASM targets as wasm-bindgen targets  (i.e. WASM for web). I guess this is a time to change that, at least on the core crates.

> Was there any specific reason for introducing the Instant dependency in this context?

Yes. `std::time::Instant` does not support WASM at all. The `instant` crate tries to do that for different WASM targets. Do you know what is the equivalent of `Instant::now()` in CosmWasm VM?

**Comment by Farhad-Shabani** [comment]
> Initially we decided to treat all WASM targets as wasm-bindgen targets (i.e. WASM for web). I guess this is a time to change that, at least on the core crates.

That would be great!

> Yes. `std::time::Instant` does not support WASM at all. The `instant` crate tries to do that for different WASM targets. Do you know what is the equivalent of `Instant::now()` in CosmWasm VM?

I don't believe there would be any equivalent, since there isn't any way to access to a local clock within the CW sandbox.

**Comment by oblique** [comment]
> I don't believe there would be any equivalent, since there isn't any way to access to a local clock within the CW sandbox.

In that case, the following check in the [`verify`](https://github.com/eigerco/celestia-node-rs/blob/ee630f2b5303a5d930ea4228c38ecf12b7b5db59/types/src/extended_header.rs#L122) method needs to be disabled for CosmWasm. Is this ok with you?

https://github.com/eigerco/celestia-node-rs/blob/ee630f2b5303a5d930ea4228c38ecf12b7b5db59/types/src/extended_header.rs#L147-L157

**Comment by Farhad-Shabani** [comment]
> In that case, the following check in the [verify](https://github.com/eigerco/celestia-node-rs/blob/ee630f2b5303a5d930ea4228c38ecf12b7b5db59/types/src/extended_header.rs#L122) method needs to be disabled for CosmWasm. Is it acceptable for you?

I think, that's fine. On our end, we can include this check by creating [an untrusted block state](https://github.com/informalsystems/tendermint-rs/blob/de10198566778ab4c861106c1576fc1a5320a1b8/light-client-verifier/src/types.rs#L90-L94) from an `ExtendedHeader` and verify it against a trusted header using this [verify_update_header](https://github.com/informalsystems/tendermint-rs/blob/9e48f176339108c4caf27821eb584fd0fa46c2e8/light-client-verifier/src/verifier.rs#L281-L295) function provided by `tendermint-light-client-verifier` library.

**Comment by oblique** [comment]
@Farhad-Shabani Can you check is everything ok now?

**Comment by Farhad-Shabani** [comment]
All good so far! Appreciate your help! :pray:
