### ISSUE TITLE
Switch node-wasm logging to tracing-web

### ISSUE THREAD

**Issue by fl0rek** [eigerco/celestia-node-rs#145]
Switch logging for wasm from `tracing-wasm` to [`tracing-web`](https://docs.rs/tracing-web/latest/tracing_web/).

**Comment by oblique** [comment]
Also it would be good for the `node-wasm` to be able to change log level dynamically. This is can be done via [tracing_subscriber::reload](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/reload/struct.Layer.html).
